language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

- name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@4.1.8
